### ISSUE TITLE
error when no arguments given to challengeutils command

### ISSUE THREAD

**Issue by diekhans** [Sage-Bionetworks/challengeutils#219]
**Describe the bug**
when challangeutils is run without an argument, it gets the error
`AttributeError: 'Namespace' object has no attribute 'func'
`
**To Reproduce**
1. run challengeutils command with no arguments

**Expected behavior**
a help message  is printed

**Screenshots**
```
% challengeutils  
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/bin/challengeutils", line 8, in <module>
    sys.exit(main())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/challengeutils/__main__.py", line 806, in main
    args.func(syn, args)
AttributeError: 'Namespace' object has no attribute 'func'

```

**Comment by thomasyu888** [comment]
Thanks for reporting this issue @diekhans .  Will look into it.

**Comment by thomasyu888** [comment]
Fixed @diekhans
